# Generated by Django 5.0.7 on 2025-05-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Use Markdown formatting. Example: **bold**, _italic_, `code`, > blockquote'),
        ),
    ]
